on:
  pull_request_target: # for OSS with public contributions   
  pull_request:   
jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1 
